### ISSUE TITLE
Refactorizar base de datos 

### ISSUE THREAD

**Issue by jordiBujaldon** [UB-ES-2022-A3/usArt#60]
La base de datos consume mucho en Azure y no llegamos a final de curso con el presupuesto. 
Falta también modelar la base de datos para que haya interacciones entre las tablas
A consecuencia se tendria de modificar los JSON y el frontend

**Comment by Manuel-AHA** [comment]
Lo he mirado, he cambiado la base de datos a MySQL para reducir costes, he adaptado el modelo y el frontend en consecuencia
